name: Candle Image Task

on:
  repository_dispatch:
    types: [candle-image-task]
  workflow_dispatch:
    inputs:
      vm_name:
        description: 'Name of the VM to run tasks on'
        required: true

jobs:
  run-candle-image-task:
    runs-on: ubuntu-latest
    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Run Candle Image Task
      run: |
        VM_NAME="${{ github.event.client_payload.vm_name || github.event.inputs.vm_name }}"
        OUTPUT=$(az vm run-command invoke \
          --resource-group githubVM \
          --name "$VM_NAME" \
          --command-id RunShellScript \
          --scripts "
                set -e
                curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y;
                echo 'Checking installation...'
                CARGO_HOME=\"\$HOME/.cargo\"
                if [ -d \"\$CARGO_HOME/bin\" ]; then
                    echo '.cargo/bin directory exists.'
                    ls -alh \"\$CARGO_HOME/bin\"
                else
                    echo '.cargo/bin directory NOT found.'
                    exit 1
                fi
                PATH=\"\$CARGO_HOME/bin:\$PATH\"
                echo \$PATH > \$HOME/.path
                source \$HOME/.path
                rustc --version || echo 'rustc not found after installation.'
                git clone https://github.com/huggingface/candle.git;
                cd candle;
                cargo build --example whisper --release || echo 'cargo build failed.';
                ls" \
          --query "value[].message" --output tsv)
        echo "Command Output:"
        echo "$OUTPUT"



    # cargo new myapp; cd myapp; ls; cargo build --example whisper --release; ls; cd target/release/examples; ls
    # - name: Deallocate VM
    #   run: |
    #     VM_NAME="${{ github.event.client_payload.vm_name || github.event.inputs.vm_name }}"
    #     az vm deallocate --resource-group githubVM --name "$VM_NAME"
