name: Check and Transfer Whisper Binary

on:
  workflow_dispatch:
    inputs:
      vm_name:
        description: 'Name of the VM to run tasks on'
        required: true
      vm_ip:
        description: 'Public IP address of the VM'
        required: true

jobs:
  check-download-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Check Whisper Binary Exists
      env:
        VM_USER: runner
        VM_IP: ${{ github.event.inputs.vm_ip }}
        SSH_PRIVATE_KEY: ${{ secrets.VM_SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        
        # SSH into the VM and list the contents of the directory
        ssh -o StrictHostKeyChecking=no $VM_USER@$VM_IP "ls -l /candle/target/release/examples/"
        
        # If the file is not found, use find command to search across the filesystem
        if ssh -o StrictHostKeyChecking=no $VM_USER@$VM_IP "test ! -f /candle/target/release/examples/whisper"; then
          echo "The whisper binary was not found at the specified path. Searching the entire filesystem..."
          ssh -o StrictHostKeyChecking=no $VM_USER@$VM_IP "find / -type f -name whisper"
        else
          echo "Whisper binary exists at the specified path."
        fi
      shell: bash

    - name: Download Whisper Binary
      if: success() # Only runs if the previous step was successful
      env:
        VM_USER: runner
        VM_IP: ${{ github.event.inputs.vm_ip }}
        SSH_PRIVATE_KEY: ${{ secrets.VM_SSH_PRIVATE_KEY }}
      run: |
        # Use SCP to copy the binary from VM to the GitHub runner
        scp -o StrictHostKeyChecking=no $VM_USER@$VM_IP:/candle/target/release/examples/whisper .
      shell: bash

    - name: Upload Whisper Binary
      if: success() # Only runs if the previous step was successful
      uses: actions/upload-artifact@v2
      with:
        name: whisper-binary
        path: ./whisper
