name: Check and Transfer Whisper Binary

on:
  workflow_dispatch:
    inputs:
      vm_name:
        description: 'Name of the VM to run tasks on'
        required: true
      vm_ip:
        description: 'Public IP address of the VM'
        required: true

jobs:
  check-download-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Check and Transfer Whisper Binary
      env:
        VM_USER: runner
        VM_IP: 172.191.177.239
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh -o StrictHostKeyChecking=no $VM_USER@$VM_IP << EOF
        # The 'find' command is more appropriate for searching files within a directory tree
        # Looking for 'whisper' binary within '/candle/target/release/'
        WHISPER_PATH=\$(find /candle/target/release/ -type f -name whisper)
        if [[ ! -z "\$WHISPER_PATH" ]]; then
          echo "Whisper binary found at: \$WHISPER_PATH"
          # Add any additional commands you need, for example, to transfer the binary
        else
          echo "Whisper binary not found in /candle/target/release/"
          exit 1
        fi
        EOF
      shell: bash


    - name: Download Whisper Binary
      if: success() # Only runs if the previous step was successful
      env:
        VM_USER: runner
        VM_IP: ${{ github.event.inputs.vm_ip }}
        SSH_PRIVATE_KEY: ${{ secrets.VM_SSH_PRIVATE_KEY }}
      run: |
        # Use SCP to copy the binary from VM to the GitHub runner
        scp -o StrictHostKeyChecking=no $VM_USER@$VM_IP:/candle/target/release/examples/whisper .
      shell: bash

    - name: Upload Whisper Binary
      if: success() # Only runs if the previous step was successful
      uses: actions/upload-artifact@v2
      with:
        name: whisper-binary
        path: ./whisper
