name: Check and Transfer Whisper Binary

on:
  workflow_dispatch:
    inputs:
      vm_name:
        description: 'Name of the VM to run tasks on'
        required: true
      vm_ip:
        description: 'Public IP address of the VM'
        required: true

jobs:
  check-download-upload:
    runs-on: ubuntu-latest
    env:
      VM_USER: runner
      VM_IP: ${{ github.event.inputs.vm_ip }}
      SSH_PRIVATE_KEY: ${{ secrets.VM_SSH_PRIVATE_KEY }}
    steps:
      - name: Setup SSH Key and Permissions
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $VM_IP >> ~/.ssh/known_hosts
        shell: bash

      - name: Check SSH Connection
        run: ssh -vvv -o StrictHostKeyChecking=no $VM_USER@$VM_IP "echo 'SSH connection successful'"
        shell: bash

      - name: Find Candle Directory in VM
        run: ssh -o StrictHostKeyChecking=no $VM_USER@$VM_IP "find / -type d -name candle 2>/dev/null"
        shell: bash

      - name: Check Whisper Binary Exists After Build
        run: ssh -o StrictHostKeyChecking=no $VM_USER@$VM_IP "ls -l ~/candle/target/release/examples/whisper"
        shell: bash

      - name: Check Whisper Binary Exists in Expected Directory
        run: |
          set +e # Allow the next command to fail without exiting the script
          ssh -o StrictHostKeyChecking=no $VM_USER@$VM_IP "ls -l /candle/target/release/examples/whisper"
          if [ $? -ne 0 ]; then
            echo "The whisper binary was not found at the specified path. Searching the entire filesystem..."
            ssh -o StrictHostKeyChecking=no $VM_USER@$VM_IP "find / -type f -name whisper"
          else
            echo "Whisper binary exists at the specified path."
          fi
        shell: bash

      - name: Download Whisper Binary
        run: scp -o StrictHostKeyChecking=no $VM_USER@$VM_IP:/candle/target/release/examples/whisper .
        shell: bash

      - name: Upload Whisper Binary
        uses: actions/upload-artifact@v2
        with:
          name: whisper-binary
          path: ./whisper
